const ExcelJS = require('exceljs');
const { MOU_LIFECYCLE_LABELS } = require('./mouLifecycle');

const FILTER_LABELS = {
  proposalId: 'MOU ID',
  q: 'Search',
  sectorLeadId: 'Sector Lead',
  changedBy: 'Changed By (user id)',
  changedByRole: 'Changed By Role',
  sector: 'Sector',
  mouStatus: 'MOU Status',
  from: 'From Date',
  to: 'To Date',
  sectorScopes: 'Jurisdiction Sectors',
};

function csvEscape(value) {
  const text = value === null || value === undefined ? '' : String(value);
  if (/[",\n\r]/.test(text)) {
    return `"${text.replace(/"/g, '""')}"`;
  }
  return text;
}

function formatFilterValue(key, value) {
  if (value === null || value === undefined || value === '') return '';
  if (key === 'mouStatus') {
    return MOU_LIFECYCLE_LABELS[value] || value;
  }
  if (key === 'sectorScopes' && Array.isArray(value)) {
    return value.join('; ');
  }
  return String(value);
}

function buildFilterSummaryLines(filters = {}, meta = {}) {
  const lines = [];
  lines.push(`Report Type: ${meta.filtered ? 'Filtered' : 'General (all matching scope)'}`);
  lines.push(`Viewer Scope: ${meta.viewer_scope || 'all'}`);
  if (meta.jurisdiction_sectors?.length) {
    lines.push(`Jurisdiction: ${meta.jurisdiction_sectors.join('; ')}`);
  }

  if (meta.proposal_id) {
    lines.push(`MOU ID: ${meta.proposal_id}`);
  }
  if (meta.proposal_label) {
    lines.push(`MOU: ${meta.proposal_label}`);
  }

  const active = Object.entries(filters).filter(([key, value]) => {
    if (key === 'sectorScopes') return false;
    if (value === null || value === undefined || value === '') return false;
    if (Array.isArray(value) && !value.length) return false;
    return true;
  });

  if (!active.length) {
    lines.push('Filters: None');
  } else {
    active.forEach(([key, value]) => {
      lines.push(`${FILTER_LABELS[key] || key}: ${formatFilterValue(key, value)}`);
    });
  }

  lines.push(`Total Records: ${meta.total ?? 0}`);
  lines.push(`Generated At: ${meta.generated_at || new Date().toISOString()}`);
  lines.push(`Generated By: ${meta.generated_by_name || ''} (${meta.generated_by_role || ''})`);
  return lines;
}

function hasActiveFilters(filters = {}) {
  return Object.entries(filters).some(([key, value]) => {
    if (key === 'sectorScopes') return false;
    if (value === null || value === undefined || value === '') return false;
    if (Array.isArray(value) && !value.length) return false;
    return true;
  });
}

function flattenLogRow(log) {
  return {
    log_id: log.id,
    date_time: log.created_at,
    mou_id: log.proposal_id,
    mou_label: log.proposal_label,
    sector: log.proposal_sector || '',
    mou_status: log.mou_lifecycle_label || log.mou_lifecycle || '',
    changed_by: log.changed_by_name,
    role: log.changed_by_role,
    action: log.action_label || log.action,
    summary: log.summary || '',
    fields_changed: (log.fields_changed || []).join('; '),
    change_details: (log.change_details || []).join(' | '),
  };
}

const DATA_COLUMNS = [
  { key: 'log_id', header: 'Log ID' },
  { key: 'date_time', header: 'Date / Time' },
  { key: 'mou_id', header: 'MOU ID' },
  { key: 'mou_label', header: 'MOU' },
  { key: 'sector', header: 'Sector' },
  { key: 'mou_status', header: 'MOU Status' },
  { key: 'changed_by', header: 'Changed By' },
  { key: 'role', header: 'Role' },
  { key: 'action', header: 'Action' },
  { key: 'summary', header: 'Summary' },
  { key: 'fields_changed', header: 'Fields Changed' },
  { key: 'change_details', header: 'Before → After' },
];

function changeLogsToCsv(report) {
  const lines = [];
  lines.push('MOU Change Logs Report');
  buildFilterSummaryLines(report.filters_applied, report.meta).forEach((line) => {
    lines.push(csvEscape(line));
  });
  lines.push('');
  lines.push(DATA_COLUMNS.map((col) => csvEscape(col.header)).join(','));
  report.logs.forEach((log) => {
    const row = flattenLogRow(log);
    lines.push(DATA_COLUMNS.map((col) => csvEscape(row[col.key])).join(','));
  });
  return lines.join('\r\n');
}

async function changeLogsToXlsx(report) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'MOU Tracking Portal';
  workbook.created = new Date();

  const info = workbook.addWorksheet('Report Info');
  info.getColumn(1).width = 28;
  info.getColumn(2).width = 80;
  info.addRow(['MOU Change Logs Report']);
  info.getRow(1).font = { bold: true, size: 14 };
  buildFilterSummaryLines(report.filters_applied, report.meta).forEach((line) => {
    const idx = line.indexOf(':');
    if (idx > -1) {
      info.addRow([line.slice(0, idx).trim(), line.slice(idx + 1).trim()]);
    } else {
      info.addRow([line, '']);
    }
  });

  const sheet = workbook.addWorksheet('Change Logs');
  sheet.columns = DATA_COLUMNS.map((col) => ({
    header: col.header,
    key: col.key,
    width: col.key === 'change_details' ? 48 : col.key === 'mou_label' ? 36 : 18,
  }));
  sheet.getRow(1).font = { bold: true };
  report.logs.forEach((log) => {
    sheet.addRow(flattenLogRow(log));
  });
  sheet.views = [{ state: 'frozen', ySplit: 1 }];

  return workbook.xlsx.writeBuffer();
}

function buildProposalExportFilename(proposalId, format) {
  const date = new Date().toISOString().slice(0, 10);
  const ext = format === 'xlsx' || format === 'xls' ? 'xlsx' : 'csv';
  return `mou-${proposalId}-change-logs-${date}.${ext}`;
}

function buildExportFilename({ filtered, format }) {
  const date = new Date().toISOString().slice(0, 10);
  const suffix = filtered ? 'filtered' : 'general';
  const ext = format === 'xlsx' || format === 'xls' ? 'xlsx' : 'csv';
  return `mou-change-logs-${suffix}-${date}.${ext}`;
}

module.exports = {
  changeLogsToCsv,
  changeLogsToXlsx,
  buildExportFilename,
  buildProposalExportFilename,
  hasActiveFilters,
  buildFilterSummaryLines,
};
