const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const { reportToCsv, formatCommentsForCsv, formatApprovalsForCsv, formatPokeResponseForCsv } =
  require('./proposalReport');

function summaryRows(report) {
  return [
    ['Proposal ID', report.proposal.id],
    ['Title', report.proposal.title],
    ['Status', report.proposal.status],
    ['Sector', report.proposal.sector],
    ['Engagement Type', report.proposal.engagement_type],
    ['Party A Name', report.parties.party_a.name],
    ['Party A Organization', report.parties.party_a.organization],
    ['Party A Email', report.parties.party_a.email],
    ['Party B Name', report.parties.party_b.name],
    ['Party B Organization', report.parties.party_b.organization],
    ['Party B Email', report.parties.party_b.email],
    ['Total Project Cost (USD)', report.value.total_project_cost_usd ?? ''],
    ['Investment Ask Equity (USD)', report.value.investment_ask_equity_usd ?? ''],
    ['Investment Ask Summary', report.value.investment_ask_summary],
    ['Executive — Company Overview', report.overview.executive_summary?.company_overview],
    ['Executive — Project Overview', report.overview.executive_summary?.project_overview],
    ['Project — Core Activity', report.overview.project_overview?.core_activity],
    ['MOU Description', report.overview.mou_description],
    ['Submitted At', report.proposal.submitted_at],
    ['Reviewed At', report.proposal.reviewed_at],
    ['Reviewed By', report.proposal.reviewed_by_name],
    ['Sector Lead Comment', report.proposal.sector_lead_comment],
    ['Report Generated At', report.generated_at],
    ['Generated By', `${report.generated_by.name} (${report.generated_by.role})`],
  ];
}

async function reportToXlsx(report) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Pakistan-China Investment Portal';
  workbook.created = new Date();

  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.columns = [
    { header: 'Field', key: 'field', width: 32 },
    { header: 'Value', key: 'value', width: 72 },
  ];
  summarySheet.getRow(1).font = { bold: true };
  summarySheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0F766E' },
  };
  summarySheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

  for (const [field, value] of summaryRows(report)) {
    summarySheet.addRow({ field, value: value ?? '' });
  }

  const activitySheet = workbook.addWorksheet('Activity Updates');
  activitySheet.columns = [
    { header: 'Activity Date', key: 'activity_date', width: 14 },
    { header: 'Title', key: 'title', width: 28 },
    { header: 'Description', key: 'description', width: 40 },
    { header: 'Status', key: 'status', width: 12 },
    { header: 'Added By', key: 'added_by_name', width: 20 },
    { header: 'Added By Role', key: 'added_by_role', width: 14 },
    { header: 'Comments', key: 'comments', width: 48 },
    { header: 'Approvals', key: 'approvals', width: 40 },
    { header: 'Poke Response', key: 'poke_response', width: 36 },
    { header: 'Support File URL', key: 'support_file_url', width: 36 },
  ];
  activitySheet.getRow(1).font = { bold: true };
  activitySheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0F766E' },
  };
  activitySheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };

  for (const activity of report.updates) {
    activitySheet.addRow({
      activity_date: activity.activity_date,
      title: activity.title,
      description: activity.description,
      status: activity.status,
      added_by_name: activity.added_by_name,
      added_by_role: activity.added_by_role,
      comments: formatCommentsForCsv(activity.comments),
      approvals: formatApprovalsForCsv(activity.approvals),
      poke_response: formatPokeResponseForCsv(activity.poke_response),
      support_file_url: activity.support_file_url || '',
    });
  }

  activitySheet.views = [{ state: 'frozen', ySplit: 1 }];
  return workbook.xlsx.writeBuffer();
}

function pdfWriteSection(doc, title, rows) {
  doc.moveDown(0.5);
  doc.fontSize(13).fillColor('#0f766e').text(title, { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#1e293b');
  for (const [label, value] of rows) {
    const text = value === null || value === undefined || value === '' ? '—' : String(value);
    doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
    doc.font('Helvetica').text(text, { width: 500 });
  }
}

function reportToPdf(report) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).fillColor('#0f172a').text('Proposal Export Report', { align: 'center' });
    doc.moveDown(0.3);
    doc
      .fontSize(11)
      .fillColor('#64748b')
      .text(`${report.proposal.title} · #${report.proposal.id}`, { align: 'center' });
    doc.moveDown(1);

    pdfWriteSection(doc, 'Parties', [
      ['Party A', `${report.parties.party_a.name} — ${report.parties.party_a.organization}`],
      ['Party A Email', report.parties.party_a.email],
      ['Party B', `${report.parties.party_b.name} — ${report.parties.party_b.organization}`],
      ['Party B Email', report.parties.party_b.email],
      ['Sector', report.proposal.sector],
      ['Status', report.proposal.status],
    ]);

    pdfWriteSection(doc, 'Investment Value', [
      ['Investment Ask Summary', report.value.investment_ask_summary],
      ['Total Project Cost (USD)', report.value.total_project_cost_usd],
      ['Equity Ask (USD)', report.value.investment_ask_equity_usd],
      ['Total Funds Required (PKR Mn)', report.value.total_funds_required_pkr_mn],
      ['Projected IRR %', report.value.projected_irr_pct],
    ]);

    pdfWriteSection(doc, 'Overview', [
      ['Venture', report.overview.venture_name],
      ['Company Overview', report.overview.executive_summary?.company_overview],
      ['Project Overview', report.overview.executive_summary?.project_overview],
      ['Core Activity', report.overview.project_overview?.core_activity],
      ['MOU Description', report.overview.mou_description],
    ]);

    doc.addPage();
    doc.fontSize(13).fillColor('#0f766e').text('Activity Updates (date-wise)', { underline: true });
    doc.moveDown(0.5);

    if (!report.updates.length) {
      doc.fontSize(10).fillColor('#64748b').text('No activity updates recorded.');
    }

    for (const activity of report.updates) {
      doc.fontSize(11).fillColor('#0f172a').font('Helvetica-Bold').text(
        `${activity.activity_date || '—'} · ${activity.title} [${activity.status}]`
      );
      doc.font('Helvetica').fontSize(10).fillColor('#334155');
      doc.text(`Added by: ${activity.added_by_name} (${activity.added_by_role})`);
      if (activity.description) {
        doc.text(activity.description, { width: 500 });
      }
      const comments = formatCommentsForCsv(activity.comments);
      if (comments) doc.text(`Comments: ${comments}`, { width: 500 });
      const approvals = formatApprovalsForCsv(activity.approvals);
      if (approvals) doc.text(`Approvals: ${approvals}`, { width: 500 });
      const poke = formatPokeResponseForCsv(activity.poke_response);
      if (poke) doc.text(`Poke response: ${poke}`, { width: 500 });
      doc.moveDown(0.6);

      if (doc.y > 700) doc.addPage();
    }

    doc.moveDown(1);
    doc
      .fontSize(9)
      .fillColor('#94a3b8')
      .text(
        `Generated ${report.generated_at} by ${report.generated_by.name} (${report.generated_by.role})`,
        { align: 'center' }
      );

    doc.end();
  });
}

module.exports = {
  reportToCsv,
  reportToXlsx,
  reportToPdf,
};
